---
env:
  browser: true
  es6: true
  node: true
  jest: true
globals:
  React: writable
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
extends:
  - eslint:recommended
  - next
  - next/core-web-vitals
  - plugin:react/recommended
  - plugin:prettier/recommended
plugins:
  - simple-import-sort
  - react
  - react-hooks
  - prettier
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  react/prop-types: off
  react/react-in-jsx-scope: off
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  react-hooks/exhaustive-deps: warn
  react/no-unescaped-entities: warn
  no-unused-vars: warn