---
env:
  browser: true
  es6: true
  node: true
  jest: true
globals:
  React: writable
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: module
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:prettier/recommended
plugins:
  - '@typescript-eslint'
  - simple-import-sort
  - react
  - react-hooks
  - prettier
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  react/react-in-jsx-scope: off
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-unsafe-argument': warn
  '@typescript-eslint/no-unsafe-assignment': warn
  '@typescript-eslint/no-unsafe-member-access': warn